//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.BestSellers = new HashSet<BestSellers>();
            this.DeliveryDetails = new HashSet<DeliveryDetails>();
            this.PaymentDetails = new HashSet<PaymentDetails>();
            this.ReceiptDetails = new HashSet<ReceiptDetails>();
        }
    
        public int BookID { get; set; }
        public string bookName { get; set; }
        public string author { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public int amount { get; set; }
        public decimal price { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public decimal receiptPrice { get; set; }
        public string description { get; set; }
        public Nullable<int> status { get; set; }
        public byte[] img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BestSellers> BestSellers { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Publishers Publishers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryDetails> DeliveryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetails> PaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptDetails> ReceiptDetails { get; set; }
    }
}
