//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debts
    {
        public int DebtID { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string creatorName { get; set; }
        public int id_dl { get; set; }
        public int DeliveryNoteID { get; set; }
        public Nullable<decimal> thanhtoan { get; set; }
    
        public virtual Agencies Agencies { get; set; }
        public virtual DeliveryNotes DeliveryNotes { get; set; }
    }
}
