//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDetails
    {
        public int DeliveryNoteID { get; set; }
        public int BookID { get; set; }
        public int amount { get; set; }
        public decimal price { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual DeliveryNotes DeliveryNotes { get; set; }
    }
}
