//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTyPHSachEntities : DbContext
    {
        public CTyPHSachEntities()
            : base("name=CTyPHSachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agencies> Agencies { get; set; }
        public virtual DbSet<BestSellers> BestSellers { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Debts> Debts { get; set; }
        public virtual DbSet<DeliveryDetails> DeliveryDetails { get; set; }
        public virtual DbSet<DeliveryNotes> DeliveryNotes { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
        public virtual DbSet<ReceiptDetails> ReceiptDetails { get; set; }
        public virtual DbSet<ReceiptNotes> ReceiptNotes { get; set; }
        public virtual DbSet<PaymentDetails> PaymentDetails { get; set; }
    }
}
