//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetails
    {
        public int ReceiptNoteID { get; set; }
        public int BookID { get; set; }
        public int receiptAmount { get; set; }
        public decimal totalPrice { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual ReceiptNotes ReceiptNotes { get; set; }
    }
}
